config/routes.rb
Ocill::Application.routes.draw do

  post 'launch/create'
  get 'launch/create_external'
  get 'launch/create'
  post 'panda/notifications'

  get 'home/show'

  devise_for :users

  post '/tinymce_assets' => 'tinymce_assets#create'
 
  resources :roles
  
  resources :courses do
    resources :roles
    post 'create_many_roles' => 'roles#create_many_roles'
    resources :units
  end

  resources :sections, only: [:show, :edit, :update]

  post 'sections/:id/duplicate_parent_activities' => 'sections#duplicate_parent_activities'
  get 'sections/:id/duplication_status' => 'sections#duplication_status'

  resources :users, only: [:index, :show] 

  resources :activities, only: [:edit, :update]

  resources :units do
    resources :drills
  end
  
  resources :drills do
    get 'read' => 'drills#read'
    member do
      get 'row/add' => 'drills#add_row'
      get 'column/add' => 'drills#add_column'
      get 'row(/:exercise_id)' => 'drills#remove_row'
      get 'column(/:header_id)' => 'drills#remove_column'
    end
    resources :attempts
    resources :exercises do
      resources :exercise_items
    end
  end

  resources :attempts
  
  resources :exercises do
    delete 'remove_audio' => 'exercises#remove_audio'
    delete 'remove_image' => 'exercises#remove_image'
    delete 'remove_video' => 'exercises#remove_video'
    resources :audio
  end
  
  resources :exercise_items do
    delete 'remove_audio' => 'exercise_items#remove_audio'
    delete 'remove_image' => 'exercise_items#remove_image'
    delete 'remove_video' => 'exercise_items#remove_video'
    resources :audio
  end

  root :to => 'home#show'

end

app/models/exercise_item.rb
class ExerciseItem < ActiveRecord::Base
  attr_accessible :graded, :header_id, :exercise_item_type, :acceptable_answers, :text, :type, :image, :audio, :video, :panda_audio_id, :options, :media_id, :media_type
  # attr_accessible  :options
  attr_accessible :position, :remove_audio, :remove_image, :remove_video

  # TODO remove "column" and "deleted_at" from db
  mount_uploader :audio, AudioUploader
  mount_uploader :video, VideoUploader
  mount_uploader :image, ImageUploader
  serialize :acceptable_answers
  serialize :options, Hash

  # default_scope where("deleted_at IS NULL")

  # scope :deleted, -> { unscoped.where("deleted_at IS NOT NULL") }

  belongs_to :exercise
  belongs_to :header
  # validates :exercise_id, :presence => true

  after_initialize :set_default_position
  before_save :cleanup_audio

  alias :parent :exercise

  def duplicate_for(exercise)
    copy = self.dup
    copy.exercise_id = exercise.id
    copy.save

  end

  def panda_audio
    @panda_audio ||= Panda::Video.find(panda_audio_id)
  end

  def audio_urls
    urls = []
    urls << self.audio_url
    urls << self.mp3
    urls << self.ogg
    urls = urls.compact.reject{|i| i.empty?}.map {|u| u.gsub(/http:/, "https:")}.uniq
  end

  def self.serialized_attr_accessor(*args)
    args.each do |method_name|
      eval "
        def #{method_name}
          (self.options || {})[:#{method_name}]
        end
        def #{method_name}=(value)
          self.options ||= {}
          self.options[:#{method_name}] = value
        end
        attr_accessible :#{method_name}
      "
    end
  end

  serialized_attr_accessor :mp3, :ogg, :horizontal

  def cleanup_audio
    if remove_audio
      self.remove_audio!
    end
  end

  def hide_text?
    # TODO Yuck.  why am I reaching into the Drill?
    self.exercise.drill.hide_text
  end

  def answers
    special_answers || acceptable_answers
  end

  def special_answers
    if self.audio.present?
      "1"
    else
      nil
    end
  end

  def set_default_position
    self.position ||= 999999
  end

  def drill
    self.exercise.drill
  end

  def siblings
    siblings = self.exercise.exercise_items
    siblings.delete(self)
    siblings
  end

  def as_json(options={})
    if options[:type] == :simple || options[:type] == :shuffle
      {
        id: self.id ,
        position: self.position ,
        text: self.text,
        graded: self.graded,
        acceptable_answers: self.acceptable_answers
      }
    else
      {
        id: self.id ,
        updated_at: self.updated_at,
        created_at: self.created_at ,
        position: self.position ,
        text: self.text,
        graded: self.graded,
        audio: self.audio,
        image: self.image,
        video: self.video,
        panda_audio_id: self.panda_audio_id,
        acceptable_answers: self.acceptable_answers
       }
    end
  end
end

app/controllers/exercise_items_controller.rb
class ExerciseItemsController < InheritedResources::Base
  load_and_authorize_resource :exercise
  load_and_authorize_resource :exercise_item, :through => :exercise
  respond_to :json

  def remove_audio
    exercise_item = process_deletions
    exercise_item.remove_audio!

    if exercise_item.save!
      flash[:notice] = "Audio file removed"
    else
      flash[:error] = "Audio file not removed"
    end
    redirect_to edit_drill_path(exercise_item.exercise.drill)
  end

  def remove_image
    exercise_item = process_deletions
    exercise_item.remove_image!

    if exercise_item.save!
      flash[:notice] = "Image file removed"
    else
      flash[:error] = "Image file not removed"
    end
    redirect_to edit_drill_path(exercise_item.exercise.drill)
  end

  def remove_video
    exercise_item = process_deletions
    exercise_item.remove_video!

    if exercise_item.save!
      flash[:notice] = "Video file removed"
    else
      flash[:error] = "Video file not removed"
    end
    redirect_to edit_drill_path(exercise_item.exercise.drill)
  end

private

  def process_deletions
    exercise_item = ExerciseItem.find(params[:exercise_item_id])
    # Remove from Kaltura
    DeleteSingleFile.new(exercise_item.media_id, exercise_item.media_type).delete
    # Clear local DB columns
    exercise_item['media_id'] = ''
    exercise_item['media_type'] = ''

    exercise_item
  end
end

app/helpers/exercise_items_helper.rb
module ExerciseItemsHelper
end

app/views/exercise_items/_form.html.erb
<%= form_for @exercise_item, :html => { :class => 'form-horizontal' }, :remote => true do |f| %>
  <%= f.hidden_field :key %>
  <div class="control-group">
    <%= f.label :graded, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :graded, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="exercise_item_audio">Audio</label>
    <div class="controls exercise_item_audio">
      <p><%= @exercise_item.audio_name %></p>
        <%= direct_upload_form_for @audio_uploader do |f| %>
          <p><%= f.file_field :audio %></p>
        <% end %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :answer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :answer, :class => 'text-field' %>
    </div>
  </div>

<% end %>

app/views/exercise_items/_save_audio_form.html.erb
<div class="control-group">
  <label class="control-label" for="exercise_item_audio">Audio:</label>
  <div class="controls exercise_item_audio <%= params[:table_cell] %>">
      <%= direct_upload_form_for @audio_uploader do |f| %>
        <p><%= f.file_field :audio %></p>
        <%= f.submit "Upload Audio", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/exercise_items/_upload_audio_form.html.erb
<div class="control-group">
  <label class="control-label" for="exercise_item_audio">Audio:</label>
  <div class="controls exercise_item_audio <%= params[:table_cell] %>">
      <%= direct_upload_form_for @audio_uploader, :html => { :target => "_blank_iframe" } do |f| %>
        <p><%= f.file_field :audio %></p>
        <%= f.submit "Upload Audio", class: "btn btn-primary", id: "submit-audio-upload" %>
      <% end %>
  </div>
</div>

app/views/exercise_items/edit.html.erb
<%- model_class = ExerciseItem -%>

<%= render :partial => 'form' %>

app/views/exercise_items/edit.js.erb
// $('#new_link').hide();
// Grab the form
form = $('form');
// Grab the modal template NOTE: this needs to be changed,
// right now it's picking up the first one.  That's not really what we want
$('#audio-upload').data('tableCell')
modal = $('.modal').first();
form.after(modal);
modal.find('.modal-body').html('<%= j render("upload_audio_form") %>');
modal.modal('toggle');

app/views/exercise_items/index.html.erb
<%- model_class = ExerciseItem -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:graded) %></th>
      <th><%= model_class.human_attribute_name(:exercise_item_type) %></th>
      <th><%= model_class.human_attribute_name(:exercise_id) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:column) %></th>
      <th><%= model_class.human_attribute_name(:answer) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @exercise_items.each do |exercise_item| %>
      <tr>
        <td><%= link_to exercise_item.id, exercise_item_path(exercise_item) %></td>
        <td><%= exercise_item.text %></td>
        <td><%= exercise_item.graded %></td>
        <td><%= exercise_item.exercise_item_type %></td>
        <td><%= exercise_item.exercise_id %></td>
        <td><%= exercise_item.position %></td>
        <td><%= exercise_item.column %></td>
        <td><%= exercise_item.answer %></td>
        <td><%=l exercise_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_exercise_item_path(exercise_item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      exercise_item_path(exercise_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_exercise_item_path,
            :class => 'btn btn-primary' %>

app/views/exercise_items/new.html.erb
<%- model_class = ExerciseItem -%>

<%= render :partial => 'form' %>

app/views/exercise_items/new.js.erb
// $('#new_link').hide();
// Grab the form
form = $('form');
// Grab the modal template NOTE: this needs to be changed, right now it's picking up the first one.  That's not really what we want
modal = $('.modal').first();
form.after(modal);
modal.find('.modal-body').html('<%= j render("audio_form") %>');
modal.modal('toggle');

app/views/exercise_items/show.html.erb
<%- model_class = ExerciseItem -%>


<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @exercise_item.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:graded) %>:</strong></dt>
  <dd><%= @exercise_item.graded %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exercise_item_type) %>:</strong></dt>
  <dd><%= @exercise_item.exercise_item_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exercise_id) %>:</strong></dt>
  <dd><%= @exercise_item.exercise_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @exercise_item.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:column) %>:</strong></dt>
  <dd><%= @exercise_item.column %></dd>
  <dt><strong><%= model_class.human_attribute_name(:answer) %>:</strong></dt>
  <dd><%= @exercise_item.answer %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              exercise_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_exercise_item_path(@exercise_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              exercise_item_path(@exercise_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>