config/routes.rb
Ocill::Application.routes.draw do

  post 'launch/create'
  get 'launch/create_external'
  get 'launch/create'
  post 'panda/notifications'

  get 'home/show'

  devise_for :users

  post '/tinymce_assets' => 'tinymce_assets#create'
 
  resources :roles
  
  resources :courses do
    resources :roles
    post 'create_many_roles' => 'roles#create_many_roles'
    resources :units
  end

  resources :sections, only: [:show, :edit, :update]

  post 'sections/:id/duplicate_parent_activities' => 'sections#duplicate_parent_activities'
  get 'sections/:id/duplication_status' => 'sections#duplication_status'

  resources :users, only: [:index, :show] 

  resources :activities, only: [:edit, :update]

  resources :units do
    resources :drills
  end
  
  resources :drills do
    get 'read' => 'drills#read'
    member do
      get 'row/add' => 'drills#add_row'
      get 'column/add' => 'drills#add_column'
      get 'row(/:exercise_id)' => 'drills#remove_row'
      get 'column(/:header_id)' => 'drills#remove_column'
    end
    resources :attempts
    resources :exercises do
      resources :exercise_items
    end
  end

  resources :attempts
  
  resources :exercises do
    delete 'remove_audio' => 'exercises#remove_audio'
    delete 'remove_image' => 'exercises#remove_image'
    delete 'remove_video' => 'exercises#remove_video'
    resources :audio
  end
  
  resources :exercise_items do
    delete 'remove_audio' => 'exercise_items#remove_audio'
    delete 'remove_image' => 'exercise_items#remove_image'
    delete 'remove_video' => 'exercise_items#remove_video'
    resources :audio
  end

  root :to => 'home#show'

end

app/views/shared/_attempter_performance.html.erb
<tr>
  <td><%= link_to performance.user.email.to_s, user_url(performance.user) if performance.present? %></td>
  <td><%= performance.total_attempts %></td>
  <td><%= performance.best_attempt.html_score.html_safe %></td>
  <td class="small-date"><%= (performance.best_attempt.created_at.to_s(:simple_date) + "<br>" + performance.best_attempt.created_at.to_s(:simple_time)).html_safe %>
  <td><%= performance.worst_attempt.html_score.html_safe %></td>
  <td class="small-date"><%= (performance.worst_attempt.created_at.to_s(:simple) + "<br>" + performance.worst_attempt.created_at.to_s(:simple_time)).html_safe  %>
  <td><%= performance.average_score %></td>  
</tr>

app/views/shared/_course_selector.html.erb
<h3>Choose Course</h3>
<hr>
<% Course.order("title ASC").find_each do |c| %>
  <%= f.radio_button :course_id, c.id.to_s, :class => "selectable-course" %>
  <%= f.label :course_id, c.title, :value => c.id.to_s %> 
<% end %>
<%= link_to "Set Course", course_url(Course.first), :id => 'course-submit', :remote => true %> 
   

app/views/shared/_drill_selector.html.erb
<div class="units-for-course units-for-course-<%= course.id %>">
  <h3>Choose a Drill from <%= course.title %></h3> 
  <hr>
  <%= submit_tag "Save", :class => 'activity-submit disabled btn btn-primary' %> 
  <% course.units.each do |u| %>
    <h4><%= u.title %></h4>
    <ul class="drills-for-unit">
      <% u.drills.each do |d| %>
        <li class="drills-in-unit" data-drill-id="<%= d.id %>"><%= d.title %> </li>
      <% end -%>
    </ul>
  <% end -%>
  <%= submit_tag "Save", :class => 'activity-submit disabled btn btn-primary' %> 
</div>

app/views/shared/_list_of_drills.html.erb
<tr>
  <td><%= link_to drill.title + " (" + drill.type_abbr + ") " , drill_path(drill), :title => "View" %></td>

  <td>
    <% if can? :create, Attempt %>
      <%= link_to t('.attempt', :default => t("helpers.links.attempt")), new_drill_attempt_path(drill), :class => 'btn btn-mini', :title => "Attempt"  %>
    <% end %>

    <% if can? :update, drill %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_drill_path(drill), :class => 'btn btn-mini', :title => "Edit" %>
    <% end %>
    
    <% if can? :destroy, drill %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                drill_path(drill),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-mini btn-danger',
                :title => "Remove" %>
    <% end %>
  </td>
</tr>

app/views/shared/_list_of_users.html.erb
<li>
  <% if can? :read, user %>
  	<%= content_tag :span, user.email %>
	<% end %>
	<% if can? :update, @course %>
		<%= link_to "User Page", user_url(user) if user.present? %>
	<% end -%> 
	
	<% if can? :manage, @course %> 
    <%= link_to icon("times"), role_path(role), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
	<% end -%>
</li>

app/views/shared/_performance.html.erb
<%= content_tag :h3, drill.title if is_unit %>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Number of Attempts</th>
      <th>Best Score</th>
      <th>(date)</th>      
      <th>Worst Score</th>
      <th>(date)</th>    
      <th>Average Score</th>
    </tr>
  </thead>
  <tbody>
    <% if performances %>
      <% performances.each do |performance| %>
        <% unless performance.not_by_learner? %>
          <%= render partial: 'shared/attempter_performance', :locals => {:performance => performance } %>
        <% end -%>
      <% end -%>
    <% end -%>
  </tbody>
</table>

app/views/shared/_remove_audio.html.erb
<%= link_to icon('times', 'white'), remove_audio_path(exercise_item), :confirm => "Are you sure you want to delete this file?", :method => :delete %>