config/routes.rb
Ocill::Application.routes.draw do

  post 'launch/create'
  get 'launch/create_external'
  get 'launch/create'
  post 'panda/notifications'

  get 'home/show'

  devise_for :users

  post '/tinymce_assets' => 'tinymce_assets#create'
 
  resources :roles
  
  resources :courses do
    resources :roles
    post 'create_many_roles' => 'roles#create_many_roles'
    resources :units
  end

  resources :sections, only: [:show, :edit, :update]

  post 'sections/:id/duplicate_parent_activities' => 'sections#duplicate_parent_activities'
  get 'sections/:id/duplication_status' => 'sections#duplication_status'

  resources :users, only: [:index, :show] 

  resources :activities, only: [:edit, :update]

  resources :units do
    resources :drills
  end
  
  resources :drills do
    get 'read' => 'drills#read'
    member do
      get 'row/add' => 'drills#add_row'
      get 'column/add' => 'drills#add_column'
      get 'row(/:exercise_id)' => 'drills#remove_row'
      get 'column(/:header_id)' => 'drills#remove_column'
    end
    resources :attempts
    resources :exercises do
      resources :exercise_items
    end
  end

  resources :attempts
  
  resources :exercises do
    delete 'remove_audio' => 'exercises#remove_audio'
    delete 'remove_image' => 'exercises#remove_image'
    delete 'remove_video' => 'exercises#remove_video'
    resources :audio
  end
  
  resources :exercise_items do
    delete 'remove_audio' => 'exercise_items#remove_audio'
    delete 'remove_image' => 'exercise_items#remove_image'
    delete 'remove_video' => 'exercise_items#remove_video'
    resources :audio
  end

  root :to => 'home#show'

end

app/controllers/exercises_controller.rb
class ExercisesController < InheritedResources::Base
  load_and_authorize_resource :drill
  load_and_authorize_resource :exercise, :through => :drill
  respond_to :html, :json
  
  def new
    @drill = Drill.find(params[:drill_id])
    @exercise = Exercise.new(drill_id: params[:drill_id])
    respond_to do |format|
      format.html { redirect_to proc { edit_drill_url(@drill, @exercise) } }
      format.js
    end
  end

  def remove_audio
    exercise = process_deletions
    exercise.remove_audio!

    if exercise.save!
      flash[:notice] = "Audio file removed"
    else
      flash[:error] = "Audio file not removed"
    end
    redirect_to edit_drill_path(exercise.drill)
  end

  def remove_image
    exercise = process_deletions
    exercise.remove_image!

    if exercise.save!
      flash[:notice] = "Image file removed"
    else
      flash[:error] = "Image file not removed"
    end
    redirect_to edit_drill_path(exercise.drill)
  end

  def remove_video
    exercise = process_deletions
    exercise.remove_video!

    if exercise.save!
      flash[:notice] = "Video file removed"
    else
      flash[:error] = "Video file not removed"
    end
    redirect_to edit_drill_path(exercise.drill)
  end

  private

  def process_deletions
    exercise = Exercise.find(params[:exercise_id])
    # Remove from Kaltura
    DeleteSingleFile.new(exercise.media_id, exercise.media_type).delete
    # Clear local DB columns
    exercise['media_id'] = ''
    exercise['media_type'] = ''

    exercise
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
  def graded_fill_drill_exercise(exercise, responses)
    spans = exercise.exercise_items.map do |ei|
      # TODO reduce number of sql queries
      if response = responses.find {|r| r.exercise_item_id.to_i == ei.id }
        '<span class="' + graded_class(response) + '">'  + response.value.to_s + '</span>' + " " + (response.correct? ? icon("ok") : icon("times"))
      else
        '<span class="left-blank"></span>' + icon("times")
      end
    end
    html = exercise.prompt_with_hints.gsub(/\[/,'{{').gsub(/\]/,'}}')
    spans.each {|span| html.sub!(/\{\{.+?\}\}/, span) }
    html
  end

  def graded_drag_drill_exercise(exercise, responses)

  end

  def graded_class(response)
    graded_class = "incorrect"
    graded_class = "correct" if response.correct?
    graded_class = "left-blank" if response.value.blank?
    graded_class
  end

  def graded_grid_drill_exercise(exercise, responses)
    html = ""
    exercise.exercise_items.each do |ei|
      if ei.answers
        response = responses.find {|r| r.exercise_item_id.to_i == ei.id }
        html += "<td>" + (response.correct? ? icon("ok") : icon("times")) + "</td>"
      else
        html += "<td>--</td>".html_safe
      end
    end
    html.html_safe
  end

  def edit_fill_drill_exercise(exercise, responses, attempt_id)
    inputs = exercise.exercise_items.map do |ei|
      response = responses.find {|r| r.exercise_item_id.to_i == ei.id }
      create_response_input(ei.id, attempt_id)
    end
    prompt = exercise.prompt_with_hints.gsub(/\[/,'{{').gsub(/\]/,'}}')
    inputs.each {|input| prompt.sub!(/\{\{.+?\}\}/, input) }
    prompt
  end

  def attempt_drag_drill_exercise(exercise, responses, attempt_id )

    inputs = exercise.exercise_items.map do |ei|
      if response = responses.find {|r| r.exercise_item_id.to_i == ei.id }
        create_response_input(ei.id, attempt_id, "text", "correct", response.value)
      end
    end
  end

  def attempt_fill_drill_exercise(exercise, responses, attempt_id)
    inputs = exercise.exercise_items.map do |ei|
      if response = responses.find {|r| r.exercise_item_id.to_i == ei.id }
        create_response_input(ei.id, attempt_id, "text", "correct", response.value)
      else
        response = Response.new( {exercise_item_id:ei.id, attempt_id: @attempt.id, value:''} )
        @attempt.responses += [response]
        create_response_input(ei.id, attempt_id)
      end
    end
    prompt = exercise.prompt_with_hints.gsub(/\[/,'{{').gsub(/\]/,'}}')
    inputs.each {|input| prompt.sub!(/\{\{.+?\}\}/, input) }
    prompt
  end

  def create_response_input(exercise_item_id, attempt_id, type="text", css_class="the_blank", value="" )
    i = rand(1...999999999)
    '
      <input id="attempt_responses_exercise_item_id" name="attempt[responses][' + i.to_s + '][exercise_item_id]" type="hidden" value="' + exercise_item_id.to_s + ' "/>

      <input class="' + css_class + '" id="attempt_responses_value" name="attempt[responses][' + i.to_s + '][value]" type="' + type + '" value="' + value + '"/>
    '
  end

  def create_grid_drill_exercises(exercise, responses)

    inputs = exercise.exercise_items.map do |ei|
      if response = responses.select {|r| r.exercise_item_id == ei.id}.first
        input = "<td class=\"finished-playing\">"
        input += create_response_input(ei.id, response.id, "hidden", "audio-played", response.value)
      else
        input= "<td>"
        response = Response.new({"exercise_item_id" => ei.id})
        input += create_response_input(ei.id, 80085, "hidden", "audio-played", "0" )
      end

      input += kaltura_audio_player(ei) if ei.media_type == Exercise::AUDIO
      input += kaltura_image_display(ei) if ei.media_type == Exercise::IMAGE
      input += kaltura_video_player(ei) if ei.media_type == Exercise::VIDEO

      text = ei.text unless exercise.drill.hide_text?
      input += content_tag(:p, text )
      input += "</td>"
    end
    inputs.join('')
  end

  def kaltura_image_display(model)
    return unless model.media_type == Exercise::IMAGE
    return if model.media_id.blank?

    host = Exercise::HOST
    partner_id = Exercise::PARTNER_ID
    media_id = model.media_id
    image_tag "http://#{host}/p/#{partner_id}/sp/#{partner_id}00/raw/entry_id/#{media_id}/version/100001"
  end

  def kaltura_audio_player(model)
    return unless model.media_type == Exercise::AUDIO
    return if model.media_id.blank?

    host = Exercise::HOST
    partner_id = Exercise::PARTNER_ID
    player_id = Exercise::AUDIO_PLAYER_ID
    media_id = model.media_id
    player_width = 400
    player_height = 100
    s = "<script src='https://#{host}/p/#{partner_id}/sp/#{partner_id}00/embedIframeJs/uiconf_id/#{player_id}/partner_id/#{partner_id}?autoembed=true&entry_id=#{media_id}&playerId=#{player_id + media_id}&width=#{player_width}&height=#{player_height}'></script>"
    raw(s)
  end

  def kaltura_video_player(model)
    return unless model.media_type == Exercise::VIDEO
    return if model.media_id.blank?

    host = Exercise::HOST
    partner_id = Exercise::PARTNER_ID
    player_id = Exercise::VIDEO_PLAYER_ID
    media_id = model.media_id
    player_width = 400
    player_height = 330
    s = "<script src='https://#{host}/p/#{partner_id}/sp/#{partner_id}00/embedIframeJs/uiconf_id/#{player_id}/partner_id/#{partner_id}?autoembed=true&entry_id=#{media_id}&playerId=#{player_id + media_id}&width=#{player_width}&height=#{player_height}'></script>"
    raw(s)
  end

  def deletable_object?(model, type)
    model.id && model['media_type'] == type
  end

end

app/views/exercises/_form.html.erb
<%= form_for @exercise, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text-field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :weight, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :weight, :class => 'text-field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :prompt, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :prompt, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :position, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :drill_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :drill_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                exercises_path, :class => 'btn' %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<%- model_class = Exercise -%>

<%= render :partial => 'form' %>

app/views/exercises/index.html.erb
<%- model_class = Exercise -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:prompt) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:drill_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= link_to exercise.id, exercise_path(exercise) %></td>
        <td><%= exercise.title %></td>
        <td><%= exercise.weight %></td>
        <td><%= exercise.prompt %></td>
        <td><%= exercise.position %></td>
        <td><%= exercise.drill_id %></td>
        <td><%=l exercise.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_exercise_path(exercise), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      exercise_path(exercise),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_exercise_path,
            :class => 'btn btn-primary' %>

app/views/exercises/new.html.erb
<%- model_class = Exercise -%>

<%= render :partial => 'form' %>

app/views/exercises/show.html.erb
<%- model_class = Exercise -%>


<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @exercise.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @exercise.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prompt) %>:</strong></dt>
  <dd><%= @exercise.prompt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @exercise.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:drill_id) %>:</strong></dt>
  <dd><%= @exercise.drill_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              exercises_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_exercise_path(@exercise), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              exercise_path(@exercise),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>