config/routes.rb
Ocill::Application.routes.draw do

  post 'launch/create'
  get 'launch/create_external'
  get 'launch/create'
  post 'panda/notifications'

  get 'home/show'

  devise_for :users

  post '/tinymce_assets' => 'tinymce_assets#create'
 
  resources :roles
  
  resources :courses do
    resources :roles
    post 'create_many_roles' => 'roles#create_many_roles'
    resources :units
  end

  resources :sections, only: [:show, :edit, :update]

  post 'sections/:id/duplicate_parent_activities' => 'sections#duplicate_parent_activities'
  get 'sections/:id/duplication_status' => 'sections#duplication_status'

  resources :users, only: [:index, :show] 

  resources :activities, only: [:edit, :update]

  resources :units do
    resources :drills
  end
  
  resources :drills do
    get 'read' => 'drills#read'
    member do
      get 'row/add' => 'drills#add_row'
      get 'column/add' => 'drills#add_column'
      get 'row(/:exercise_id)' => 'drills#remove_row'
      get 'column(/:header_id)' => 'drills#remove_column'
    end
    resources :attempts
    resources :exercises do
      resources :exercise_items
    end
  end

  resources :attempts
  
  resources :exercises do
    delete 'remove_audio' => 'exercises#remove_audio'
    delete 'remove_image' => 'exercises#remove_image'
    delete 'remove_video' => 'exercises#remove_video'
    resources :audio
  end
  
  resources :exercise_items do
    delete 'remove_audio' => 'exercise_items#remove_audio'
    delete 'remove_image' => 'exercise_items#remove_image'
    delete 'remove_video' => 'exercise_items#remove_video'
    resources :audio
  end

  root :to => 'home#show'

end

app/models/drill.rb
class Drill < ActiveRecord::Base
  attr_accessible :instructions, :unit_id, :position, :prompt, :title, :exercises_attributes, :type, :headers_attributes, :options

  DRAG_DRILL = 'DragDrill'
  GRID_DRILL = 'GridDrill'
  FILL_DRILL = 'FillDrill'

  serialize :options, Hash

  belongs_to :unit
  alias :parent :unit

  has_many :exercises, :dependent => :destroy, :autosave => true, :order => "position ASC"
  alias :children :exercises
  accepts_nested_attributes_for :exercises, allow_destroy: true

  has_many :activities
  has_many :attempts
  has_many :attempters, :through => :attempts, :uniq => true, :source => :user
  has_many :exercise_items, :through => :exercises, :autosave => true
  has_many :images, :as => :imageable
  has_many :headers, :order => "position ASC", :dependent => :destroy, :autosave => true
  accepts_nested_attributes_for :headers, allow_destroy: true

  validates :unit_id, :presence => true
  validates :title, :presence => true

  before_save :set_default_title
  before_save :set_default_position
  after_commit :flush_user_navigation_caches

  def duplicate_for(unit)
    copy = self.dup
    copy.unit_id = unit.id
    copy.save
    
    self.exercises.each do |exercise|
      exercise.duplicate_for(copy)
    end
  end


  def self.serialized_attr_accessor(*args)
    args.each do |method_name|
      eval "
        def #{method_name}
          (self.options || {})[:#{method_name}]
        end
        def #{method_name}=(value)
          self.options ||= {}
          self.options[:#{method_name}] = value
        end
        attr_accessible :#{method_name}
      "
    end
  end

  serialized_attr_accessor :rtl, :hide_text, :retain_correct, :horizontal

  def direction
    direction = self.rtl == "1" ? 'dir="rtl"' : 'dir="ltr"'
    direction.html_safe
  end

  def type_abbr
    case self.type
    when "GridDrill"
      "Grid"
    when "FillDrill"
      "FITB"
    else
      ""
    end
  end

  def retain_correct?
    self.retain_correct == "1"
  end

  def hide_text?
    self.hide_text == "1"
  end

  def horizontal?
    self.horizontal == "1"
  end

  def answers
    self.exercise_items.map {|exercise_item| exercise_item.answer}.flatten
  end

  def course
    self.unit.course unless self.unit.nil?
  end

  def rows
    self.exercises.size
  end

  def as_json(options={}, current_user="")
    {
      created_at: self.created_at ,
      header_row: self.header_row ,
      id: self.id ,
      instructions: self.instructions ,
      options:  self.options ,
      position: self.position ,
      prompt: self.prompt ,
      title: self.title ,
      unit_id: self.unit_id ,
      updated_at: self.updated_at,
      exercises: self.exercises.as_json(thingers)
     }
  end


private
  def set_default_title
    self.title = "Default Title" if self.title.blank?
  end

  def set_default_position
    self.position ||= Drill.maximum(:id).to_i + 1
  end

private
  def flush_user_navigation_caches
    User.flush_all_navigation_caches
  end
end

app/models/grid_drill.rb
class GridDrill < Drill

  def self.model_name
    Drill.model_name
  end

  def add_column(header_name='Header')
    self.save!
    header = self.headers.create(:title => header_name)
    if self.exercises.empty?
      self.exercises.create(:title => "Title", :prompt => "Prompt")
    end
    self.exercises.each do |exercise|
      exercise_item = exercise.exercise_items.create(:header_id => header.id)
    end
  end

  def add_row(prompt='Prompt')
    self.save!
    exercise = self.exercises.create(:title => "Title", :prompt => prompt)
    exercise.make_cells_for_row
  end

  def remove_row(exercise_id)
    self.save!
    exercise = self.exercises.find(exercise_id)
    exercise.destroy
  end

  def remove_column(header_id)
    self.save!
    exercise_items = self.exercise_items.where(header_id: header_id)
    exercise_items.each do |ei|
      ei.destroy
    end
    headers = self.headers.where(id: header_id)
    headers.each do |h|
      h.destroy
    end
  end
 
  def columns
    headers.size
  end
end

app/controllers/drills_controller.rb
class DrillsController < InheritedResources::Base
  load_and_authorize_resource
  respond_to :json

  def show
    @drill = Drill.find(params[:id])
  end

  def read
    @drill = Drill.includes( exercises: :exercise_items ).find(params[:drill_id])
    options = {}
    options[:type] = params[:type].to_sym
    options[:current_user] = current_user
    # needs to shuffle first time round
    options[:first_attempt] = request.referrer.split('/').include?('new') unless request.referrer.blank?

    respond_to do |format|
      format.html
      if params[:type]
        format.json { render json: @drill.as_json(options) }
      else
        format.json { render json: @drill.as_json }
      end
     # format.json { render json: @drill.as_json }
    end
  end

  def new
    if params[:unit_id]
      @unit = Unit.find(params[:unit_id])
      @drill = @unit.drills.build

    else
      @drill = Drill.new
    end
  end

  def index

  end

  def create
    if @drill.type == "DragDrill"

      if @drill.save
        redirect_to edit_drill_url(@drill)
        return
      end
    end

    super do |format|
      format.html { render :action => "edit" }
    end

  end


  def update
    @drill = Drill.find(params[:id])
    has_exercises = @drill.exercises.count > 0 ? true : false
    add_answers_to_params unless current_user.is_learner?

    if @drill.update_attributes(params[:drill])
      update_drag_exercise_positions(has_exercises)
      flash[:notice] = "Successfully updated the drill."
    end
    respond_with(@drill) do |format|
      format.html { render :action => "edit" }
      format.json { render json: @drill.as_json }
    end
  end

  def destroy
    @drill = Drill.find(params[:id])
    unit = @drill.unit
    @drill.destroy
    super do |format|
      format.html { redirect_to unit_url(unit) }
    end
  end

  def add_column
    @drill = Drill.find(params[:id])
    if @drill.update_attributes(params[:drill])
      flash[:notice] = "Drill Updated."
      if @drill.add_column
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
          format.js
        end
      else
        flash[:error] = "Drill Was Not Updated."
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
        end
      end
    else
      flash[:error] = "Drill Update Failed."
    end

  end

  def add_row
    @drill = Drill.find(params[:id])
    if @drill.update_attributes(params[:drill])
      if @row = @drill.add_row
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
        end
      end
    else
      flash[:error] = "Drill Was Not Updated."
      respond_to do |format|
        format.html { redirect_to(:action => 'edit') }
      end
    end
  end

  def remove_row
    @drill = Drill.find(params[:id])
    if @drill.update_attributes(params[:drill])
      if @row = @drill.remove_row(params[:exercise_id])
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
        end
      end
    else
      flash[:error] = "Drill Was Not Updated."
      respond_to do |format|
        format.html { redirect_to(:action => 'edit') }
      end
    end
  end

  def remove_column
    @drill = Drill.find(params[:id])
    if @drill.update_attributes(params[:drill])
      if @drill.remove_column(params[:header_id])
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to(:action => 'edit') }
        end
      end
    else
      flash[:error] = "Drill Was Not Updated."
      respond_to do |format|
        format.html { redirect_to(:action => 'edit') }
      end
    end
  end

private

  def add_answers_to_params
    exercises_attr = params['drill']['exercises_attributes']
    return if exercises_attr.nil?

    # Iterate each exercise
    exercises_attr.each_with_index do |attrs, index|
      return unless attrs && attrs.last['exercise_items_attributes']

      new_items = {}
      exercises_items_attr = attrs.last['exercise_items_attributes']

      # Process exercise items
      exercises_items_attr.each_with_index do |item, i|
        new_items[i.to_s] = exercises_items_attr[i.to_s].merge({'acceptable_answers' => [i]})
      end

      attrs.last['exercise_items_attributes'] = new_items
    end
  end

  def update_drag_exercise_positions(has_exercises)
    return unless @drill.type == Drill::DRAG_DRILL
    return if params['drill']['exercises_attributes'].nil?

    current_positions = @drill.exercises.map{|e| [e.id.to_s, e.position.to_s]}.to_h
    if has_exercises
      incoming_positions = params['drill']['exercises_attributes'].map{|ea| [ea[1]['id'], ea[0] ] }.to_h
    else
      incoming_positions = current_positions.each_with_index.map{|k, i| [k.first, i] }.to_h
    end

    ids_to_update = incoming_positions.map{|k,v| k }
    values_to_update = incoming_positions.map{|k,v| { position: v }}
    Exercise.update(ids_to_update, values_to_update) unless current_positions == incoming_positions
  end

end

app/helpers/drills_helper.rb
module DrillsHelper
  def show_headers(drill)
    html = "<thead><tr>"
    html += '<th scope="col">' + ( drill.title || "&nbsp;" ) + '</th>'
    drill.headers.each do |h|
      html += '<th scope="col">'
      html += ( h.title || "&nbsp;" ) + '</th>'
    end
    html += '</tr></thead>'
  end

  def before_exercise_wrapper(drill, width="200" )
    direction = (drill.rtl == "1") ? '"rtl"' : '"ltr"'
    case drill.type
    when "GridDrill"
      html = '<table dir=' + direction + 'class ="table" width="' + width + '" border="1" summary="A set of exercises for this'
      html += drill.type.to_s.titleize + '">'
      html += show_headers(drill).to_s
    when "FillDrill"
      html = "<ol dir=#{direction}>"
    else
      html = "&nbsp;"
    end
  end
#  TODO remove this method unless you decide to use it
  def drill_breadcrumbs(drill)
    html = '<div class="breadcrumbs">'
    html += '<span class="crumb course" data-course-id="' + drill.course.id.to_s + '">'
    html += drill.course.title.to_s
    html += '</span>'
    html += '<span class="crumb unit icon-arrow-right" data-unit-id="' + drill.unit.id.to_s + '">'
    html += drill.unit.title.to_s
    html += '</span>'
    html += '<span class="last-crumb drill icon-arrow-right" data-drill-id="' + drill.id.to_s + '">'
    html += drill.title.to_s
    html += '</span>'
    html += '</div><!-- .breadcrumbs -->'
    html.html_safe
  end

  def after_exercise_wrapper(drill)
    case drill.type
    when "GridDrill"
      html = '</table>'
    when "FillDrill"
      html = '</ol>'
    else
      html = "&nbsp;"
    end
  end
end

app/views/drills/grid_drills/_exercise_fields.html.erb
<tr>
  <td class="cell" id="cell-c0-r<%= f.object.row %>">
    <span class="remove-row">
      <%= link_to icon('remove', 'white'), controller: "drills", action: "remove_row", exercise_id: f.object.id %>
    </span>
      <%= f.text_field :prompt, :class => 'text-field' %>
      <%= f.hidden_field :position, value: nested_child_index(f) %>
  </td>
  
  <%= f.fields_for :exercise_items do |builder| %>
    <%= render nested_folder(@drill) + 'exercise_item_fields', :f => builder %>
  <% end %>
<tr>

app/views/drills/grid_drills/_exercise_item_fields.html.haml
- table_cell = "cell-c" + (f.object.header.position + 1).to_s + "-r" + (f.object.exercise.position + 1).to_s

%td.cell{:id => table_cell}
  = f.text_field :text, :class => 'text-field'

  = f.hidden_field :position, value: nested_child_index(f)

  = link_to icon("headphones", "white").html_safe, "#", :class => "add-audio-field"
  = link_to icon("camera","white").html_safe, "#", :class => "add-image-field"
  = link_to icon("film","white").html_safe, "#", :class => "add-video-field"

  = kaltura_audio_player(f.object)
  - if deletable_object?(f.object, 'audio')
    = (link_to icon('times', 'white'),                                |
      exercise_item_remove_audio_path(f.object),                      |
      :confirm => "Are you sure you want to delete this audio file?", |
      :method => :delete )                                            |

  = kaltura_video_player(f.object)
  - if deletable_object?(f.object, 'video')
    = (link_to icon('times', 'white'),                                |
      exercise_item_remove_video_path(f.object),                      |
      :confirm => "Are you sure you want to delete this audio file?", |
      :method => :delete )                                            |

  = kaltura_image_display(f.object)
  - if deletable_object?(f.object, 'image')
    = (link_to icon('times', 'white'),                                |
      exercise_item_remove_image_path(f.object),                      |
      :confirm => "Are you sure you want to delete this audio file?", |
      :method => :delete )                                            |

  = f.file_field :audio, :class => "hidden audio-upload-field upload-field"
  = f.file_field :image, :class => "hidden image-upload-field upload-field"
  = f.file_field :video, :class => "hidden video-upload-field upload-field"

app/views/drills/grid_drills/_fields.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th class="cell cell-c0-r0"></th>
      <%= f.fields_for :headers do |builder| %>
        <%= render nested_folder(@drill) + 'header_fields', f: builder %>
      <% end %>
      <th class="add_column"><%= link_to "Add Column", column_add_drill_path(@drill) ,class: "submit-form" %></th>
    </tr>
  </thead>
  <tbody>
    <%= f.fields_for :exercises do |builder| %>
        <%= render nested_folder(@drill) + 'exercise_fields', :f => builder %>
    <% end %>
    <tr>
      <td class="add_row"><%= link_to "Add Row", row_add_drill_path(@drill), class: "submit-form" %></td>
    </tr>
  </tbody>
</table>

app/views/drills/grid_drills/_header_fields.html.erb
<th class="cell" id="cell-c<%= f.object.column %>-r0" >
  <%= f.text_field :title, :class => 'text-field' %>
  <%= f.hidden_field :position, value: nested_child_index(f) %>
  <span class="remove-column">
    <%= link_to icon('remove', 'white'), controller: "drills", action: "remove_column", header_id: f.object.id %>
  </span>

</th>

app/views/drills/grid_drills/_options.html.erb
<%= f.label :options %>
<div class="checkbox-controls">
  <%= f.label :rtl, :class => 'control-label' %>
  <%= f.check_box :rtl, :class => 'set-rtl' %>
  <%= f.label :hide_text, :class => 'control-label' %>
  <%= f.check_box :hide_text, :class => 'set-show-text' %>
  <%= f.check_box :retain_correct, :class => 'set-retain-correct hidden' %>
</div>

app/views/drills/grid_drills/_show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th class="cell cell-c0-r0"></th>
      <% drill.headers.each do |header| %>
        <%= render '/drills/grid_drills/show_headers', header: header %>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% drill.exercises.each do |exercise| %>
        <%= render '/drills/grid_drills/show_exercises',  :exercise => exercise %>  
    <% end %>
  </tbody>
</table>

      

app/views/drills/grid_drills/_show_exercises.html.erb
<tr>
  <th scope="row"><%= exercise.prompt.html_safe || "&nbsp;" %></th> 
  <% exercise.exercise_items.sort_by(&:position).each do |ei| %>
    <td><%= content_tag(:p, ei.text ) %><%= audio_tag( ei.audio_urls ) %></td>
  <% end %>
</tr>

app/views/drills/grid_drills/_show_headers.html.erb
<th class="cell" id="cell-c<%= header.column %>-r0" >
  <%= content_tag(:p, header.title, :class => 'text-field') %>
</th>